### ISSUE TITLE
Script sometimes stops working + Towers don't place on Garden

### ISSUE THREAD

**Issue by Kinetic1000** [trimbe/btdb2-xp#1]
just left the script running and sometimes it stops on the tower xp screen and it looks like OK is being pressed (the button gets smaller then goes back to its normal size) but nothing happens

Microsoft Windows [Version 10.0.19042.1348]
(c) Microsoft Corporation. All rights reserved.

C:\Users\redacted\Downloads\btdb2-xp-master>python bot.py
Opponent disconnected, attempting to reset
Found ok button
Opponent disconnected, attempting to reset
Traceback (most recent call last):
  File "C:\Users\redacted\Downloads\btdb2-xp-master\bot.py", line 201, in <module>
    ok_pos = find_template_center('templates/ok2.png')
  File "C:\Users\redacted\Downloads\btdb2-xp-master\bot.py", line 64, in find_template_center
    res = cv2.matchTemplate(cvImg, template, cv2.TM_CCOEFF_NORMED)
cv2.error: OpenCV(4.5.4) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1175: error: (-215:Assertion failed) _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width in function 'cv::matchTemplate'

C:\Users\redacted\Downloads\btdb2-xp-master>

**Comment by Kinetic1000** [comment]
also on garden the tower doesn't place because it's too close to the track

**Comment by trimbe** [comment]
I'm not sure how you're hitting that error, unless you're resizing the window very small or something? 

The map detection will occasionally break (I think because of animations in the pixel I'm sampling), but in my experience it happens very rarely so I haven't gotten around to fixing that. Especially with the impending nerf to surrender farming.

**Comment by Kinetic1000** [comment]
> I'm not sure how you're hitting that error, unless you're resizing the window very small or something?
> 
> The map detection will occasionally break (I think because of animations in the pixel I'm sampling), but in my experience it happens very rarely so I haven't gotten around to fixing that. Especially with the impending nerf to surrender farming.

the window resizes smaller when the script starts though it's probably supposed to do that, and the issue happens every time on garden
